version: "3.9"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_rust_scraper_domemploi
    ports:
      - 5432:5432
    volumes:
      - scraper_domemploi__data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_USER=user
      - POSTGRES_DB=db

volumes:
  scraper_domemploi__data:
